config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  get   '/syllabify/:language_name'  => 'landings#syllabify'         , as: :syllabify
  post  '/syllabify/:language_name'  => 'landings#syllabify'         , as: :syllabify_remote


  get   '/syllabifications/:syllabification_id'  => 'landings#show_syllabification'         , as: :show_syllabification
  post   '/alter_syllabification/:syllabification_id'  => 'landings#alter_syllabification'         , as: :alter_syllabification_remote
  post '/get_similar_syllabifications/:word_id'  => 'landings#get_similar_syllabifications' , as: :get_similar_syllabifications

  post   '/clear_skipped_words'  => 'landings#clear_skipped_words'         , as: :clear_skipped_words

  post   '/mark_word/:word_id'  => 'landings#mark_word'         , as: :mark_word

  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

  root 'landings#index'
end

app/views/shared/_recent_syllabification.html.erb
  <h5 style="text-align: left"> 
  <%= recent_syllabification.word.value %>  →  <%= recent_syllabification.value %>
  <%= link_to( 
              content_tag(:span , "" , :class => "glyphicon glyphicon glyphicon-new-window" ) ,
              show_syllabification_path( recent_syllabification ) , 
              :class => "btn  btn-xs" , 
              :style => "float: right" ) %>
  </h5>
  <h6 style="text-align: left"><small> <%= time_ago_in_words(recent_syllabification.created_at) %> ago </small></h6>
  <hr>

app/views/shared/_recent_syllabifications.html.erb
  <%for recent_syllabification in recent_syllabifications %>
        <%= render :partial => "shared/recent_syllabification"  , :locals => { :recent_syllabification => recent_syllabification } %>
  <%end%>

app/views/shared/_similar_syllabifications.html.erb
<%if word_syllabification_hash.size > 0 %>
	<ul>
		<% word_syllabification_hash.each do |key , value| %> 
			<li><%= key %> → <%= value %></li>
		<%end%>
	</ul>
<% else %>
		Sorry Nothing found!
<% end %>

app/views/shared/_similar_syllabifications_modal.html.erb
 <div class="modal fade" id="similar-syllabifications-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <h4 class="modal-title" id="myModalLabel">Few Similar Words Already Tagged</h4>
       </div>
       <div class="modal-body">
          <div id="similar-syllabifications" style="font-size: 25px;">

            
          </div>
            <div class="text-center">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Done!</button>
            </div>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_update_word_card.html.erb
  <% word = syllabification.word %>

  <%if not word.nil? %>
      <div class="col-xs-4 col-sm-4 lr_padding_zero">

          <%= link_to( 
              content_tag(:span , "" , :class => "glyphicon glyphicon-home" ) ,
              "/" , 
              :class => "btn btn-info" , 
              :style => "float: left; margin: 2px;" ) %>
      </div>

      <div class="col-xs-4 col-sm-4 text-center lr_padding_zero">
             <h3 style="margin-top: -15px; ">
             <span class="label label-default " > 
                   <b> <%= word.value %> → <%= syllabification.value %> </b> 
             </span>
             </h3>
      </div>

      <div class="col-xs-4 col-sm-4 lr_padding_zero">

          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#report-modal" , style="float: right; margin: 2px;" >
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>     
          </button>

      </div>

       <%= render :partial => "shared/word_report_modal" , :locals => {:word => word} %>

  <%end%>


  <span style="visibility:hidden" id="syllabification_id">
    <%= syllabification.id %>
  </span>




  <div class="container text-center">

       		<div class="row">
       		</div>
       		<div class="row" style="padding-top: 60px ; padding-bottom: 60px ; ">
      		    <div id="word_<%= word.id %>">
                  <%= render :partial => "shared/word" , :locals => { :word => word } %>
                </div>          	  		
            </div>
       		<div class="row" style="padding-top: 10px ; padding-bottom: 20px ; " >
                  <%if word.suggestion %>
                      <p style="margin: 0px"><b>Suggestion for ( <%= word.value%> ):</b></p>
                      <p style="margin: 0px"><%= word.suggestion %></p>
                  <%end%>
                  <b><p style="margin: 0px ; font-size: 100% ;"><%= link_to("Need Similars ?" , get_similar_syllabifications_path(word.id) , :method => :post , :remote => true ) %></b>
                  <%= render :partial => "shared/similar_syllabifications_modal" %>
       		</div>
       		<div class="row">

                <button type="button" class="btn btn-danger" aria-label="Left Align" id="destroy">
                  <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"> Destroy </span>
                </button>

                <button type="button" class="btn btn-success" aria-label="Left Align" id="update">
                  <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"> Update </span>
                </button>
       		</div>

  </div>



<script type="text/javascript">
  $(document).ready(function(){

        $( "#update" ).click(function() {
              $(this).prop('disabled', true);

              var letters = $('#word').children();
              var syllabified_word = "";
              for(i=0;i<letters.length;i++){
                syllabified_word = syllabified_word + letters[i].innerText;
              }
              var syllabification_id = $('#syllabification_id').text();

              $.ajax({
                type: "POST",
                url: "/alter_syllabification/" + syllabification_id ,
                data: { submit_type: "update" ,
                        syllabified_text: syllabified_word
                },
                dataType: "script"
              });
        });

        $( "#destroy" ).click(function() {
              $(this).prop('disabled', true);

              var syllabification_id = $('#syllabification_id').text();
                            
              $.ajax({
                type: "POST",
                url: "/alter_syllabification/" + syllabification_id ,
                data: { submit_type: "destroy" 
                },
                dataType: "script"
              });

        });


    });

</script>

app/views/shared/_word.html.erb
<div id="word" style="font-size: 12.5vmin " >
	<font > <%= word.value %> </font>
</div>


<script type="text/javascript">
$('#word').html('<span>' + $('#word').text().split('').join('</span><span>') + '</span>').find('span').click(function() {
    if ($(this).next().text() == '-') {
        $(this).next().remove();
    } else {
        $(this).after('<span>-</span>');
    }
	}
);
</script>

app/views/shared/_word_card.html.erb
  <%if not word.nil? %>
      
      <div class="col-xs-4 col-sm-4 lr_padding_zero">
          <button type="button" class="btn btn-default" aria-label="Left Align" id="session-pin" , style="float: left; margin: 2px;" >
              <span class="glyphicon glyphicon-pushpin" aria-hidden="true"><%= number_of_skipped_words %></span>    
          </button>

          <%= link_to( 
              content_tag(:span , "" , :class => "glyphicon glyphicon-refresh" ) ,
              clear_skipped_words_path , 
              :class => "btn btn-info" , 
              :style => "float: left; margin: 2px;" , 
              :method => :post , 
              :remote => true) %>
      </div>

      <div class="col-xs-4 col-sm-4 text-center lr_padding_zero">
             <h3 style="margin-top: -15px; " >
                <span class="label label-default"> 
                      <b style="font-size: 90%;"> <%= completed + 1%> / <%= total %> </b> 
                </span>

             </h3>
      </div>

      <div class="col-xs-4 col-sm-4 lr_padding_zero">
          <button type="button" class="btn btn-default" aria-label="Left Align" id="session-pin" , style="float: right; margin: 2px;">
             <span class="glyphicon glyphicon-saved" aria-hidden="true"><%= word.syllabifications_count%></span> 
          </button>

          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#report-modal" , style="float: right; margin: 2px;" >
                  <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>     
          </button>

      </div>


       <%= render :partial => "shared/word_report_modal" , :locals => {:word => word} %>




  <%end%>


  <span style="visibility:hidden" id="word_id">
    <%= word.id%>
  </span>



  <div class="container text-center">

    <% if completed != total %>
       		<div class="row">
       		</div>
       		<div class="row" style="padding-top: 60px ; padding-bottom: 60px ; ">
      		    <div id="word_<%= word.id %>">
                  <%= render :partial => "shared/word" , :locals => { :word => word } %>
                </div>          	  		
            </div>
       		<div class="row" style="padding-top: 10px ; padding-bottom: 20px ; " >
         			<div>
                  <%if word.suggestion %>
                      <p style="margin: 0px"><b>Suggestion for ( <%= word.value%> ):</b></p>
                      <p style="margin: 0px"><%= word.suggestion %></p>
                  <%end%>
                  <b><p style="margin: 0px ; font-size: 100% ;"><%= link_to("Need Similars ?" , get_similar_syllabifications_path(word.id) , :method => :post , :remote => true ) %></b>
                  <%= render :partial => "shared/similar_syllabifications_modal" %>
        		  </div>
       		</div>
       		<div class="row">

                <button type="button" class="btn btn-danger" aria-label="Left Align" id="refresh">
                  <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"> Refresh</span>
                </button>

                <button type="button" class="btn btn-warning" aria-label="Left Align" id="skip">
                  <span class="glyphicon glyphicon-circle-arrow-right" aria-hidden="true"> Skip</span>
                </button>

                <button type="button" class="btn btn-success" aria-label="Left Align" id="save">
                  <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"> Save</span>
                </button>
       		</div>
    <%else%>
        <div class="row" style="padding-top: 60px ; padding-bottom: 60px ; ">           
            <h1 style="font-size: 50px"> No Word Left !  </h1>
        </div>
    <%end%>

  </div>



<script type="text/javascript">
  $(document).ready(function(){
    language_name = $("#language_name").text().trim();

        $( "#save" ).click(function() {
              $(this).prop('disabled', true);

              var letters = $('#word').children();
              var syllabified_word = "";
              for(i=0;i<letters.length;i++){
                syllabified_word = syllabified_word + letters[i].innerText;
              }
              var word_id = $('#word_id').text();         

              $.ajax({
                type: "POST",
                url: "/syllabify/" + language_name ,
                data: { submit_type: "save" ,
                        language_name: language_name,
                        word_id: word_id ,
                        syllabified_text: syllabified_word
                },
                dataType: "script"
              });
        });

        $( "#skip" ).click(function() {
              $(this).prop('disabled', true);

              word_id = $("#word_id").text().trim();
                            
              $.ajax({
                type: "POST",
                url: "/syllabify/" + language_name ,
                data: { submit_type: "skip" ,
                        word_id: word_id 
                },
                dataType: "script"
              });

        });


        $( "#refresh" ).click(function() {
              $(this).prop('disabled', true);

              word_id = $("#word_id").text().trim();          
              $.ajax({
                type: "POST",
                url: "/syllabify/" + language_name ,
                data: { submit_type: "refresh" ,
                        word_id: word_id 
                },
                dataType: "script"
              });
        });


    });

</script>

app/views/shared/_word_report_modal.html.erb
 <div class="modal fade" id="report-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog">
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
         <h4 class="modal-title" id="myModalLabel">Report / Mark Word</h4>
       </div>
       <div class="modal-body">
            <%= form_tag( mark_word_path(word) , method: "post" , :class => "form-group" , :remote => true) do %>
                <br>
                <%= label_tag 'category' %>
                <br>
                <%= radio_button_tag 'category', 'word_wrong' , true %> Word shown is wrong / has mistake
                <br>
                <%= radio_button_tag 'category', 'suggestion_wrong' %> Suggestion shown is complete different
                <br>
                <%= radio_button_tag 'category', 'confusing' %> Very Confusing
                <br>
                <%= radio_button_tag 'category', 'other' %> Others
                <br><br>
                <%= label_tag 'report_note' %>
                <%= text_area_tag(:report_note , nil , :class => "form-control" , :placeholder => "Please add helper note in report") %>
                <div class="text-center">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                      <%= submit_tag("Submit" , :class => "btn btn-primary" ) %>
                </div>
            <% end %>
       </div>
     </div>
   </div>
 </div>